### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by ochorocho** [mtarnovan/dokku-nodeexporter#1]
Hey,

i tried to change the port because 9100 is already taken by gitlabs builtin nodeexporter.

So i changed `DOKKU_NODEEXPORTER_DEFAULT_PORT` in `commands` and disabled/enabled the plugin but i still get `address already in use`

´´´
Starting nodeexporter on port 9110 ...
Error response from daemon: driver failed programming external connectivity on endpoint nodeexporter (8aa7a2a4e7afd11d5a5fe2ff773774b87a7485b71bb0637c34624dec85403c93): Error starting userland proxy: listen tcp 0.0.0.0:9100: bind: address already in use
Error: failed to start containers: nodeexporter
´´´

How can i change the port?

**Comment by mtarnovan** [comment]
Try setting `DOKKU_NODEEXPORTER_PORT`, `DOKKU_NODEEXPORTER_DEFAULT_PORT ` is a default fallback.

**Comment by mtarnovan** [comment]
Also, you don't need to edit the `commands` file, you can just do:

```
DOKKU_NODEEXPORTER_PORT=9101 dokku nodeexporter:start
```

**Comment by ochorocho** [comment]
Ok, that works now. Thanks :-)
